Tenemos un diccionario que contiene los gastos mensuales de distintas divisiones de una empresa. Cada divisi√≥n est√° identificada por un nombre y su gasto mensual.

datos = {
    "Marketing": 32000,
    "Ventas": 45000,
    "Desarrollo de Producto": 62000,
    "Soporte T√©cnico": 25000,
    "Recursos Humanos": 15000,
    "IT": 50000,
    "Operaciones": 47000,
    "Investigaci√≥n y Desarrollo": 55000
}
Realiza los siguientes pasos para explorar y manipular los datos:

üìä Crea una serie de pandas a partir del diccionario datos y ll√°mala gastos_mensuales.

üßê Imprime la siguiente informaci√≥n de la serie gastos_mensuales:

üî¢ Tama√±o de la serie para verificar cu√°ntas divisiones hay.
üìè Tipo de dato de la serie para asegurarte de que todos los datos son num√©ricos.
üè∑Ô∏è Divisiones incluidas en la serie.
üîç Usando diferentes m√©todos de indexaci√≥n obt√©n la siguiente informaci√≥n:

üíº Gastos de Ventas, IT e Investigaci√≥n y Desarrollo.
üìà Gastos desde Marketing hasta Recursos Humanos.
üõ†Ô∏è Gastos desde Desarrollo de Producto hasta Operaciones.
üöÄ Gastos desde Soporte T√©cnico hasta la √∫ltima divisi√≥n.

In [ ]:
import pandas as pd

In [ ]:
datos = {
    "Marketing": 32000,
    "Ventas": 45000,
    "Desarrollo de Producto": 62000,
    "Soporte T√©cnico": 25000,
    "Recursos Humanos": 15000,
    "IT": 50000,
    "Operaciones": 47000,
    "Investigaci√≥n y Desarrollo": 55000
}

# Crea una serie de pandas a partir del diccionario datos y ll√°mala gastos_mensuales.

gastos_mensuales = pd.Series(datos)
gastos_mensuales

#Tama√±o de la serie para verificar cu√°ntas divisiones hay.

gastos_mensuales.size

#üìè Tipo de dato de la serie para asegurarte de que todos los datos son num√©ricos.

gastos_mensuales.dtype

# üè∑Ô∏è Divisiones incluidas en la serie.

gastos_mensuales.index

# Usando diferentes m√©todos de indexaci√≥n obt√©n la siguiente informaci√≥n:

# üíº Gastos de Ventas, IT e Investigaci√≥n y Desarrollo.
# üìà Gastos desde Marketing hasta Recursos Humanos.
# üõ†Ô∏è Gastos desde Desarrollo de Producto hasta Operaciones.
# üöÄ Gastos desde Soporte T√©cnico hasta la √∫ltima divisi√≥n.

gastos_mensuales[["Ventas", "IT", "Investigaci√≥n y Desarrollo"]]

gastos_mensuales[:"Recursos Humanos"]

gastos_mensuales["Desarrollo de Producto":]

gastos_mensuales["Soporte T√©cnico":]

Soporte T√©cnico               25000
Recursos Humanos              15000
IT                            50000
Operaciones                   47000
Investigaci√≥n y Desarrollo    55000
dtype: int64

Reto 2

Considera el siguiente conjunto de datos que representa varios proyectos en una empresa de software. Cada proyecto tiene:

Un nombre √∫nico.
Una fase actual.
Un costo estimado.
Una duraci√≥n estimada en d√≠as.
import pandas as pd

# Datos de proyectos
datos = {
    'Fase Actual': ['Dise√±o', 'Desarrollo', 'Testing', 'Lanzamiento', 'Mantenimiento'],
    'Costo Estimado': [20000, 50000, 15000, 30000, 10000],
    'Duraci√≥n Estimada': [30, 90, 15, 20, 60]  # Duraci√≥n en d√≠as
}
Realiza los siguientes pasos para gestionar y analizar los datos de proyectos:

üìä Crear el dataframe con √≠ndices personalizados:

Utiliza cualquier nombre para los 5 proyectos como √≠ndices.
Imprime el dataframe inicial.
üìä A√±ade una nueva columna al dataframe llamada 'Riesgo de Retraso': que eval√∫e la duraci√≥n estimada de cada proyecto. Si la duraci√≥n es superior a 50 d√≠as, asigna un riesgo de "Alto", de lo contrario, ser√° "Bajo".

Puedes utilizar un list comprehension para evaluar cada fila del DataFrame y asignar el riesgo correspondiente.

['Alto' if x > 50 else 'Bajo' for x in proyectos['Duraci√≥n Estimada']]
üîÑ Actualiza la columna 'Costo Estimado': con nuevos valores basados en revisiones recientes del presupuesto.

‚ùå Elimina la columna 'Duraci√≥n Estimada': del DataFrame.

In [ ]:
datos = {
    'Fase Actual': ['Dise√±o', 'Desarrollo', 'Testing', 'Lanzamiento', 'Mantenimiento'],
    'Costo Estimado': [20000, 50000, 15000, 30000, 10000],
    'Duraci√≥n Estimada': [30, 90, 15, 20, 60]  # Duraci√≥n en d√≠as
}

print(datos)

print("______________")
# Crear el dataframe con √≠ndices personalizados:

proyectos = pd.DataFrame(datos, index = ['Proyecto A', 'Proyecto B', 'Proyecto C', 'Proyecto D', 'Proyecto E'])
proyectos
print(proyectos)

print("______________")

# A√±adir columna "Riesgo de Retraso

proyectos['Riesgo de Retraso'] = ['Alto' if x > 50 else 'Bajo' for x in proyectos['Duraci√≥n Estimada']]
proyectos

print("______________")


# Actualiza la columna 'Costo Estimado': con nuevos valores basados en revisiones recientes del presupuesto.

proyectos['Costo Estimado'] = [25000, 60000, 20000, 40000, 15000]
print(proyectos)

print("______________")

# Elimina la columna 'Duraci√≥n Estimada': del DataFrame.

proyectos = proyectos.drop(columns=["Duraci√≥n Estimada"])
print(proyectos)

{'Fase Actual': ['Dise√±o', 'Desarrollo', 'Testing', 'Lanzamiento', 'Mantenimiento'], 'Costo Estimado': [20000, 50000, 15000, 30000, 10000], 'Duraci√≥n Estimada': [30, 90, 15, 20, 60]}
______________
              Fase Actual  Costo Estimado  Duraci√≥n Estimada
Proyecto A         Dise√±o           20000                 30
Proyecto B     Desarrollo           50000                 90
Proyecto C        Testing           15000                 15
Proyecto D    Lanzamiento           30000                 20
Proyecto E  Mantenimiento           10000                 60
______________
______________
              Fase Actual  Costo Estimado  Duraci√≥n Estimada Riesgo de Retraso
Proyecto A         Dise√±o           25000                 30              Bajo
Proyecto B     Desarrollo           60000                 90              Alto
Proyecto C        Testing           20000                 15              Bajo
Proyecto D    Lanzamiento           40000                 20              Bajo
Proyecto E  Mantenimiento           15000                 60              Alto
______________
              Fase Actual  Costo Estimado Riesgo de Retraso
Proyecto A         Dise√±o           25000              Bajo
Proyecto B     Desarrollo           60000              Alto
Proyecto C        Testing           20000              Bajo
Proyecto D    Lanzamiento           40000              Bajo
Proyecto E  Mantenimiento           15000              Alto

Imagina que trabajas en una empresa de bienes ra√≠ces y te han asignado la tarea de analizar un conjunto de datos sobre los precios de viviendas para identificar tendencias y patrones que puedan influir en las estrategias de venta y marketing. Este an√°lisis te permitir√° proporcionar recomendaciones basadas en datos para mejorar la toma de decisiones en la empresa. Tu jefe te ha solicitado un informe detallado con tus conclusiones individuales, destacando los hallazgos m√°s relevantes.

Acciones que el programa debe realizar:

Cargar un conjunto de datos de precios de viviendas desde un archivo CSV.
Realizar una limpieza b√°sica de los datos, eliminando duplicados y manejando valores faltantes.
Crear series a partir de las columnas del DataFrame y calcular estad√≠sticas b√°sicas como la media y la mediana.
Utilizar m√©todos avanzados de indexaci√≥n para filtrar y seleccionar subconjuntos espec√≠ficos de datos.
A√±adir y modificar columnas en el DataFrame para incluir c√°lculos adicionales, como el precio por metro cuadrado.
Para ello, el programa debe seguir estos pasos:

Cargar y limpiar datos. Utiliza Pandas para cargar los datos desde el archivo CSV proporcionado. Realiza una limpieza b√°sica para asegurar la calidad de los datos.
Crear y analizar series. Extrae y analiza las series de inter√©s, calculando estad√≠sticas b√°sicas que sean relevantes para el an√°lisis.
Filtrar y seleccionar datos. Aplica m√©todos avanzados de indexaci√≥n para filtrar y seleccionar subconjuntos de datos que cumplan con ciertos criterios en espec√≠fico.
A√±adir y modificar columnas. Crea nuevas columnas para realizar c√°lculos adicionales que proporcionen mayor detalle y contexto al an√°lisis.
Redacci√≥n del informe. Redacta un informe detallado con tus conclusiones individuales, destacando los hallazgos m√°s relevantes y c√≥mo pueden influir en las decisiones estrat√©gicas de la empresa

In [ ]:
import pandas as pd

In [ ]:
df_csv = pd.read_csv('/content/sample_data/california_housing_train.csv')
df_csv.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df_excel = pd.read_excel('/content/drive/MyDrive/Newbedu/Casas usadas - RM Mayo 2020.xlsx')
df_excel.head()

,Comuna,Link,Tipo_Vivienda,N_Habitaciones,N_Ba√±os,N_Estacionamientos,Total_Superficie_M2,Superficie_Construida_M2,Valor_UF,Valor_CLP,Direcci√≥n,Qui√©n_Vende,Corredor
0,Calera de Tango,https://chilepropiedades.cl/ver-publicacion/ve...,Casa,5.0,6.0,3,5000.0,440,12200.0,351360000,"Calera de Tango, Queilen",Gabriela Mellado V.,Zenpro Propiedades
1,Calera de Tango,https://chilepropiedades.cl/ver-publicacion/ve...,Casa,6.0,6.0,6,5000.0,430,13000.0,374400000,"Calera de Tango, Queilen",Gabriela Mellado V.,Zenpro Propiedades
2,Calera de Tango,https://chilepropiedades.cl/ver-publicacion/ve...,Casa,3.0,3.0,No,2027.0,140,10300.0,296640000,"Calera de Tango, Avenida calera de tango con...",Alonso Baeza Rivera y C√≠a. Ltda. (Kennedy),Alonso Baeza Rivera y C√≠a. Ltda. (Kennedy)
3,Calera de Tango,https://chilepropiedades.cl/ver-publicacion/ve...,Casa,8.0,6.0,No,5000.0,480,21500.0,619200000,"Calera de Tango, Paradero 14 1/2/5 kilometros ...",RED Gesti√≥n Propiedades,Red Gesti√≥n Propiedades
4,Calera de Tango,https://chilepropiedades.cl/ver-publicacion/ve...,Casa,3.0,2.0,3,5000.0,196,9100.0,262080000,"Calera de Tango, Condominio El Tr√©bol de Caler...",Gabriela Mellado V.,Zenpro Propiedades

In [ ]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1139 entries, 0 to 1138
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Comuna                    1139 non-null   object
 1   Link                      1139 non-null   object
 2   Tipo_Vivienda             1139 non-null   object
 3   N_Habitaciones            1131 non-null   float64
 4   N_Ba√±os                   1118 non-null   float64
 5   N_Estacionamientos        1067 non-null   object
 6   Total_Superficie_M2       1102 non-null   float64
 7   Superficie_Construida_M2  1103 non-null   object
 8   Valor_UF                  1139 non-null   float64
 9   Valor_CLP                 1139 non-null   int64
 10  Direcci√≥n                 1102 non-null   object
 11  Qui√©n_Vende               1139 non-null   object
 12  Corredor                  1139 non-null   object
dtypes: float64(4), int64(1), object(8)
memory usage: 115.8+ KB

In [ ]:
# LIMPIEZA DE DATOS

# Eliminar duplicados
df = df_excel.drop_duplicates()

# Dejar s√≥lo valores NO Nulos
df = df_excel.dropna()

# CREAR Y ANALIZAR SERIES
Valor_CLP = df["Valor_CLP"]  # Precio en Pesos Chilenos
Total_Superficie_M2 = df["Total_Superficie_M2"]  # Metros_cuadrados

# C√°lculo de estad√≠sticas b√°sicas
media_precio = Valor_CLP.mean()
mediana_precio = Valor_CLP.median()
print(f"Media del precio: {media_precio}")
print(f"Mediana del precio: {mediana_precio}")
media_superficie = Total_Superficie_M2.mean()
mediana_superficie = Total_Superficie_M2.median()
print(f"Media de la superficie: {media_superficie}")
print(f"Mediana de la superficie: {mediana_superficie}")
viviendas_caras = Valor_CLP > media_precio
viviendas_caras = df[viviendas_caras]
print(viviendas_caras)

print('____________________________________________________________')

# A√ëADIR Y MODIFICAR COLUMNAS
# Agregar una nueva columna con el precio por metro cuadrado
df["precio_por_m2"] = df["Valor_CLP"] / df["Total_Superficie_M2"]

# Calcular la mediana del precio por metro cuadrado
mediana_precio_por_m2 = df["precio_por_m2"].median()
print(f"Mediana del precio por metro cuadrado: {mediana_precio_por_m2}")
print(df.head())

# GENERAR INFORME DE HALLAZGOS
informe = f"""
An√°lisis de precios de viviendas:
- Media de los precios: {media_precio}
- Mediana de los precios: {mediana_precio}
- Total de viviendas analizadas: {len(df)}
- Viviendas con precios superiores a la media: {len(viviendas_caras)}
"""
print(informe)

Media del precio: 309424573.22718054
Mediana del precio: 210240000.0
Media de la superficie: 884.9565922920892
Mediana de la superficie: 300.0
               Comuna                                               Link  \
0     Calera de Tango  https://chilepropiedades.cl/ver-publicacion/ve...
1     Calera de Tango  https://chilepropiedades.cl/ver-publicacion/ve...
3     Calera de Tango  https://chilepropiedades.cl/ver-publicacion/ve...
5     Calera de Tango  https://chilepropiedades.cl/ver-publicacion/ve...
7     Calera de Tango  https://chilepropiedades.cl/ver-publicacion/ve...
...               ...                                                ...
1134         Vitacura  https://chilepropiedades.cl/ver-publicacion/ve...
1135         Vitacura  https://chilepropiedades.cl/ver-publicacion/ve...
1136         Vitacura  https://chilepropiedades.cl/ver-publicacion/ve...
1137         Vitacura  https://chilepropiedades.cl/ver-publicacion/ve...
1138         Vitacura  https://chilepropiedades.cl/ver-publicacion/ve...

     Tipo_Vivienda  N_Habitaciones  N_Ba√±os N_Estacionamientos  \
0             Casa             5.0      6.0                  3
1             Casa             6.0      6.0                  6
3             Casa             8.0      6.0                 No
5             Casa             3.0      2.0                 No
7             Casa             5.0      4.0                 No
...            ...             ...      ...                ...
1134          Casa             4.0      3.0                 No
1135          Casa             3.0      2.0                 No
1136          Casa             6.0      3.0                 No
1137          Casa             5.0      3.0                 No
1138          Casa             4.0      2.0                 No

      Total_Superficie_M2 Superficie_Construida_M2  Valor_UF  Valor_CLP  \
0                  5000.0                      440   12200.0  351360000
1                  5000.0                      430   13000.0  374400000
3                  5000.0                      480   21500.0  619200000
5                  5000.0                      170   11800.0  339840000
7                  5000.0                      650   14450.0  416160000
...                   ...                      ...       ...        ...
1134                389.0                      211   20000.0  576000000
1135                325.0                      120   22000.0  633600000
1136                638.0                      242   19900.0  573120000
1137                338.0                      230   18500.0  532800000
1138                400.0                      215   19890.0  572832000

                                              Direcci√≥n  \
0                              Calera de Tango, Queilen
1                              Calera de Tango, Queilen
3     Calera de Tango, Paradero 14 1/2/5 kilometros ...
5          Calera de Tango, Lonquen Sur/Calera de Tango
7     Calera de Tango, Camino loreto/condominio sant...
...                                                 ...
1134              Vitacura, Ibiza Candelaria Goyenechea
1135                 Vitacura, Islas Galapagos/Vitacura
1136                  Vitacura, Vitacura/Filomena Comas
1137                   Vitacura, Lo Arcaya/Av. Vitacura
1138  Vitacura, Candelaria Goyenechea -Luis Carrera-...

                     Qui√©n_Vende                    Corredor
0            Gabriela Mellado V.          Zenpro Propiedades
1            Gabriela Mellado V.          Zenpro Propiedades
3        RED Gesti√≥n Propiedades     Red Gesti√≥n Propiedades
5      Mauricio Pino Propiedades   Mauricio Pino Propiedades
7       Pro Partners Propiedades    Pro Partners Propiedades
...                          ...                         ...
1134         Vivaqui Propiedades         Vivaqui Propiedades
1135  Francisco Vial Propiedades  Francisco Vial Propiedades
1136     RED Gesti√≥n Propiedades     Red Gesti√≥n Propiedades
1137     RED Gesti√≥n Propiedades     Red Gesti√≥n Propiedades
1138    Cata Brochet Propiedades    Cata Brochet Propiedades

[352 rows x 13 columns]
____________________________________________________________
Mediana del precio por metro cuadrado: 643721.4334009466
            Comuna                                               Link  \
0  Calera de Tango  https://chilepropiedades.cl/ver-publicacion/ve...
1  Calera de Tango  https://chilepropiedades.cl/ver-publicacion/ve...
2  Calera de Tango  https://chilepropiedades.cl/ver-publicacion/ve...
3  Calera de Tango  https://chilepropiedades.cl/ver-publicacion/ve...
4  Calera de Tango  https://chilepropiedades.cl/ver-publicacion/ve...

  Tipo_Vivienda  N_Habitaciones  N_Ba√±os N_Estacionamientos  \
0          Casa             5.0      6.0                  3
1          Casa             6.0      6.0                  6
2          Casa             3.0      3.0                 No
3          Casa             8.0      6.0                 No
4          Casa             3.0      2.0                  3

   Total_Superficie_M2 Superficie_Construida_M2  Valor_UF  Valor_CLP  \
0               5000.0                      440   12200.0  351360000
1               5000.0                      430   13000.0  374400000
2               2027.0                      140   10300.0  296640000
3               5000.0                      480   21500.0  619200000
4               5000.0                      196    9100.0  262080000

                                           Direcci√≥n  \
0                           Calera de Tango, Queilen
1                           Calera de Tango, Queilen
2  Calera de Tango, Avenida calera de tango   con...
3  Calera de Tango, Paradero 14 1/2/5 kilometros ...
4  Calera de Tango, Condominio El Tr√©bol de Caler...

                                  Qui√©n_Vende  \
0                         Gabriela Mellado V.
1                         Gabriela Mellado V.
2  Alonso Baeza Rivera y C√≠a. Ltda. (Kennedy)
3                     RED Gesti√≥n Propiedades
4                         Gabriela Mellado V.

                                     Corredor  precio_por_m2
0                          Zenpro Propiedades   70272.000000
1                          Zenpro Propiedades   74880.000000
2  Alonso Baeza Rivera y C√≠a. Ltda. (Kennedy)  146344.351258
3                     Red Gesti√≥n Propiedades  123840.000000
4                          Zenpro Propiedades   52416.000000

An√°lisis de precios de viviendas:
- Media de los precios: 309424573.22718054
- Mediana de los precios: 210240000.0
- Total de viviendas analizadas: 986
- Viviendas con precios superiores a la media: 352

<ipython-input-16-53d18246df3d>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["precio_por_m2"] = df["Valor_CLP"] / df["Total_Superficie_M2"]